package analyze-react-boundary:check;

interface types {
	record position {
		line: u32,
		character: u32,
	}

	record range {
		start: position,
		end: position,
	}

	record component-analysis {
		name: string,
		is-client-component: bool,
		range: range,
	}

	record import-analysis {
		identifier: list<string>,
		source: string,
		source-span: range,
	}

	record jsx-usage {
		component-name: string,
		range: range,
	}

	record analysis-result {
		imports: list<import-analysis>,
		components: list<component-analysis>,
		jsx-usages: list<jsx-usage>,
	}
}

world analyze-react-boundary {
	use types.{analysis-result};

	export types;

	import log: func(msg: string);

	export analyze: func(content: list<u8>, extension: string) -> result<analysis-result, string>;
}
