package analyze-react-boundary:check;

interface types {
	record component-analysis {
		name: string,
		is-client-component: bool,
	}

	record import-analysis {
		identifier: list<string>,
		source: string,
	}

	record analysis-result {
		imports: list<import-analysis>,
		components: list<component-analysis>,
	}
}

world analyze-react-boundary {
	use types.{analysis-result};

	export types;

	import log: func(msg: string);

	export analyze: func(content: list<u8>, extension: string) -> result<analysis-result, string>;
}
