name: CI/Rust

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Check Build
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Install wasm32-unknown-unknown target
        run: rustup target add wasm32-unknown-unknown

      - name: Build Rust code
        run: cargo build --target wasm32-unknown-unknown --release

  test:
    name: Run Tests
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run tests
        run: cargo test

  lint:
    name: Check Lint
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Run Clippy
        run: cargo clippy --all-targets --all-features -- -D warnings

  format:
    name: Check Format
    runs-on: ubuntu-24.04-arm
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Check code format
        run: cargo fmt --all -- --check
